version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_BIP110_MEMPOOL_IP
      APP_PORT: $APP_BIP110_MEMPOOL_PORT

  web:
    image: paulscode/mempool-bip110-frontend:v3.2.1.1@sha256:2dd5315ec11fa584bcd9446f46723580058cd1d999cb57e24dddd8106a110a79
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    environment:
      FRONTEND_HTTP_PORT: $APP_BIP110_MEMPOOL_PORT
      BACKEND_MAINNET_HTTP_HOST: $APP_BIP110_MEMPOOL_API_IP
      BACKEND_MAINNET_HTTP_PORT: "8999"
      NGINX_PORT: $APP_BIP110_MEMPOOL_PORT
      NGINX_HOSTNAME: $APP_BIP110_MEMPOOL_API_IP
    depends_on:
      - api
      - db
    networks:
      default:
        ipv4_address: $APP_BIP110_MEMPOOL_IP

  api:
    image: paulscode/mempool-bip110-backend:v3.2.1.1@sha256:d9909486ad9d8f71b211dc13ff88d24d59573fad284ba63d2e093f65b5602ca3
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    environment:
      # Bitcoin Core connection (provided by Umbrel)
      CORE_RPC_HOST: $APP_BITCOIN_NODE_IP
      CORE_RPC_PORT: $APP_BITCOIN_RPC_PORT
      CORE_RPC_USERNAME: $APP_BITCOIN_RPC_USER
      CORE_RPC_PASSWORD: $APP_BITCOIN_RPC_PASS

      # Electrum connection (provided by Umbrel)
      ELECTRUM_HOST: $APP_ELECTRS_NODE_IP
      ELECTRUM_PORT: $APP_ELECTRS_NODE_PORT
      ELECTRUM_TLS: "false"

      # Database connection
      DATABASE_ENABLED: "true"
      DATABASE_HOST: $APP_BIP110_MEMPOOL_DB_IP
      DATABASE_PORT: "3306"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"

      # Mempool backend config
      MEMPOOL_HTTP_PORT: "8999"
      MEMPOOL_CACHE_DIR: "/backend/cache"
      MEMPOOL_BACKEND: "electrum"
      MEMPOOL_NETWORK: "mainnet"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: "52560"
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "info"
      MEMPOOL_AUTOMATIC_POOLS_UPDATE: "true"
      MEMPOOL_RUST_GBT: "true"
      MEMPOOL_CPFP_INDEXING: "false"
      MEMPOOL_AUDIT: "false"
      MEMPOOL_ALLOW_UNREACHABLE: "true"

      # Disable GeoIP (databases not bundled)
      MAXMIND_ENABLED: "false"

      NODE_OPTIONS: "--max-old-space-size=2048"
    depends_on:
      - db
    networks:
      default:
        ipv4_address: $APP_BIP110_MEMPOOL_API_IP

  db:
    image: mariadb:10.5.21@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "moneyprintergobrrr"
    volumes:
      - ${APP_DATA_DIR}/mysql/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: $APP_BIP110_MEMPOOL_DB_IP
